# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Challenge datasciences test
short_description: Challenge IA destiné aux étudiants Marseillais
description: templates/description.html
evaluation_details: templates/evaluation.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: "Les candidats sont classés selon la mAP (mean average precision) obtenue par leur modèle."
evaluation_script: "evaluation_script.zip"
remote_evaluation: False
is_docker_based: False
start_date: 2021-07-01 09:00:00
end_date: 2021-11-10 23:59:59
published: False

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["mAP"],
        "default_order_by": "mAP",
      }

challenge_phases:
  - id: 1
    name: Détection d'antennes
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-04-01 00:10:00
    end_date: 2021-09-15 23:59:59
    test_annotation_file: annotations/test_data_devsplit.csv
    codename: detection_antenna
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: False
      - name: method_description
        is_visible: False
      - name: project_url
        is_visible: False
      - name: publication_url
        is_visible: False
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".csv"

dataset_splits:
  - id: 1
    name: Train antenna
    codename: train_antenna

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: False
